version: '2'
services:
  dpslaenderverzeichnis-app:
    image: dpslaenderverzeichnis
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@dpslaenderverzeichnis-oracle:1521:dpsLaenderverzeichnis
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 11000:11000
